ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'GEL',
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC DEFAULT 1,
  ADD COLUMN IF NOT EXISTS subtotal_gel NUMERIC,
  ADD COLUMN IF NOT EXISTS vat_amount_gel NUMERIC,
  ADD COLUMN IF NOT EXISTS total_amount_gel NUMERIC;
