import { Router } from "express";
import { z } from "zod";
import { supabaseAdmin } from "../services/supabase.service.js";
import { requireAccounting } from "./accounting.routes.js";

const router = Router();

// ── Purchase Order Creation (PO + items atomic) ──
const poItemSchema = z.object({
  product_name: z.string().min(1),
  product_sku: z.string().optional().nullable(),
  quantity_ordered: z.number().positive(),
  unit_cost: z.number().nonnegative(),
  vat_rate: z.number().nonnegative(),
  vat_amount: z.number().nonnegative(),
  line_total: z.number().nonnegative(),
});

const poSchema = z.object({
  supplier_id: z.string().uuid(),
  order_date: z.string().min(1),
  expected_date: z.string().optional().nullable(),
  subtotal: z.number().nonnegative(),
  vat_amount: z.number().nonnegative(),
  total_amount: z.number().nonnegative(),
  currency: z.string().default('GEL'),
  notes: z.string().optional().nullable(),
  items: z.array(poItemSchema).min(1),
});

router.post('/po', requireAccounting, async (req: any, res) => {
  const parsed = poSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: 'არასწორი მონაცემები', details: parsed.error.issues });
  }
  const { items, ...poHeader } = parsed.data;

  // Create PO (po_number auto-generated by DB trigger)
  const { data: po, error: poErr } = await supabaseAdmin
    .from('purchase_orders')
    .insert({
      po_number: '',
      status: 'DRAFT',
      ...poHeader,
    })
    .select()
    .single();

  if (poErr) return res.status(500).json({ error: poErr.message });

  // Insert items linked to the PO
  const poItems = items.map((item) => ({ po_id: po.id, ...item }));
  const { error: itemsErr } = await supabaseAdmin.from('purchase_order_items').insert(poItems);

  if (itemsErr) {
    // Rollback header
    await supabaseAdmin.from('purchase_orders').delete().eq('id', po.id);
    return res.status(500).json({ error: itemsErr.message });
  }

  res.json({ success: true, purchase_order: po });
});

// ── PO Status Change ──
const poStatusSchema = z.object({
  status: z.enum(['DRAFT', 'APPROVED', 'SENT', 'RECEIVED', 'CANCELLED', 'COMPLETED']),
});

router.patch('/po/:id/status', requireAccounting, async (req: any, res) => {
  const parsed = poStatusSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: 'არასწორი სტატუსი' });
  }

  const { error } = await supabaseAdmin
    .from('purchase_orders')
    .update({ status: parsed.data.status })
    .eq('id', req.params.id);

  if (error) return res.status(500).json({ error: error.message });
  res.json({ success: true });
});

// ── Goods Receipt Creation (GRN + items atomic) ──
const grnItemSchema = z.object({
  po_item_id: z.string().uuid().optional().nullable(),
  product_id: z.string().uuid().optional().nullable(),
  product_name: z.string().min(1),
  quantity_received: z.number().positive(),
  unit_cost: z.number().nonnegative(),
  notes: z.string().optional().nullable(),
});

const grnSchema = z.object({
  po_id: z.string().uuid(),
  supplier_id: z.string().uuid(),
  receipt_date: z.string().min(1),
  notes: z.string().optional().nullable(),
  items: z.array(grnItemSchema).min(1),
});

router.post('/grn', requireAccounting, async (req: any, res) => {
  const parsed = grnSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: 'არასწორი მონაცემები', details: parsed.error.issues });
  }
  const { items, ...grnHeader } = parsed.data;

  const { data: grn, error: grnErr } = await supabaseAdmin
    .from('goods_receipts')
    .insert({
      grn_number: '',
      status: 'DRAFT',
      ...grnHeader,
    })
    .select()
    .single();

  if (grnErr) return res.status(500).json({ error: grnErr.message });

  const grnItems = items.map((item) => ({ grn_id: grn.id, ...item }));
  const { error: itemsErr } = await supabaseAdmin.from('goods_receipt_items').insert(grnItems);

  if (itemsErr) {
    await supabaseAdmin.from('goods_receipts').delete().eq('id', grn.id);
    return res.status(500).json({ error: itemsErr.message });
  }

  res.json({ success: true, goods_receipt: grn });
});

// ── GRN Status Change ──
const grnStatusSchema = z.object({
  status: z.enum(['DRAFT', 'CONFIRMED', 'CANCELLED']),
});

router.patch('/grn/:id/status', requireAccounting, async (req: any, res) => {
  const parsed = grnStatusSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: 'არასწორი სტატუსი' });
  }

  const { error } = await supabaseAdmin
    .from('goods_receipts')
    .update({ status: parsed.data.status })
    .eq('id', req.params.id);

  if (error) return res.status(500).json({ error: error.message });
  res.json({ success: true });
});

export default router;
